source "https://rubygems.org"

# Specify your gem's dependencies in naga_whatsapp.gemspec.
gemspec

gem "sprockets-rails"

# Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
gem "rubocop-rails-omakase", require: false

# Start debugger with binding.b [https://github.com/ruby/debug]
gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

