class GiveInventoryCategories < ActiveRecord::Migration[7.2]
  def up
    room_inventories = Inventory.where(name: ["Teratak Bonda", "Kesidang", "Teratai", "Zen", "Sunrise", "Sasterawan", "Evensong", "Rahsiah", "Durian Runtuh", "Senjja", "Naga Home", "Khemah", "Day Visitor - Half Day", "Day Visitor - Full Day", "Best Deal: Curi Curi Week Days!", "Ramadhan Special", "Best Deal: Togethertime Week Ends!", "Conferencing Facilities"])
    room_inventories.update_all({category: "Rooms"})
  
    other_inventories = Inventory.where(name: ["Open Ended Booking", "Hike into Lata Berembun - 5 minutes drive away", "Additional Bed", "Trek to the B24 Liberator Bomber - Overnight or half a day", "Coal Barbecue Setup", "Steamboat", "Hot Plate", "Sofa Bed", "A pet guest", "Extra Bed", "Special Request!!!!", "Temuan River Trek - 5 minutes drive away", "Purchased Beverages for Client", "Photography", "Meeting Room", "Hike up Gunung Angsi - 30 minutes drive away", "Baby Crib", "Tent - 4/5 persons", "Jungle hammock - 1person", "Breakfast rebate required", "Campsite Bedding Kit - For Tent", "BBQ facilities at Pool", "Tent - 2/3 persons", "Multipurpose Room Use", "Guide for trekking", "Gift Voucher"])
    other_inventories.update_all({category: "Other"})
    
    food_inventories = Inventory.where(name: ["Indian", "Custom Lunch Option", "Malay Breakfast", "Western / Kristang Lunch", "Chinese Lunch", "Indian Lunch", "Indian Breakfast", "Chinese Breakfast", "Malay Dinner", "Western / Kristang Dinner", "Miscellaneous Transport", "Malay Lunch", "Indian Dinner", "Custom Dinner Option", "Custom Breakfast Option", "Custom Tea Option", "All Day Meals Package", "Barbecue Meat and Vege", "Chinese Meal", "Indian Meal", "Single Meal", "Vegetarian Meal", "Menu D", "BBQ Ubi Keledek - BBQ Sweet Potato", "MD - Beef Rendang", "ME - Spicy Chicken", "Western Meal 1", "WB - Chicken Chop", "MC - Chicken Rendang", "Meal Option", "Terung Sambal - Sambal Aubergine (V)", "Chicken Chop (Breast)", "BBQ Ikan Siakap - Siakap Fish BBQ", "Sides - Fruit Salad (V)", "Soto Ayam - Chicken Rice Stew", "Bihun goreng - Fried Vermicelli Noodles", "Deep fried Fish fillet", "Satay Ayam - Chicken Satay (10 sticks)", "BBQ Ikan Tilapia - BBQ Tilapia Fish", "BBQ Ayam - BBQ Chicken", "Rendang Ayam - Chicken Rendang", "Satay Daging - Beef Satay (10 sticks)", "BBQ Kambing - BBQ Lamb", "BBQ Labu - BBQ Pumpkin", "Excursion Meal Pack", "Daging Kicap - Beef with Dark Soy Sauce", "Sambal Udang - Shrimp Sambal", "Spaghetti Meatballs + Grilled Chicken (Breast)", "Gulai Daging - Coconut Milk Beef", "Ayam Sambal - Sambal Chicken", "Sambal Udang - Sambal Shrimp", "Rendang Daging - Beef Rendang", "Kari Ayam - Chicken Curry", "Vegetarian Spagetthi Marinara (V)", "Sambal Ikan Tenggiri - Tenggiri Fish Sambal", "Sides - Fruit Salad (V) - for two", "Nasi goreng ikan masin - Salted fish fried rice", "Group Catering", "Vegetarian Meal Set", "Group Set Teh Buah - Tea Set Local Fruits", "Group Set Teh Kuih - Tea Set Local Cakes - for two", "Vegetarian Curry Puff", "Chicken Curry Puff", "Jackfruit Curry with Rice - Vegetarian", "Tuak", "Nasi goreng kampung - Traditional village fried rice", "Sambal Tempeh with Rice - Vegetarian", "Pumpkin Curry with Rice - Vegetarian", "Uncle Manz BBQ Lamb 250gm - Premarinated raw meats", "Uncle Manz BBQ Chicken Quarter Chicken - Premarinated raw meats", "Side order - veggies", "Side orders for BBQ - sweet potato / corn"])
    food_inventories.update_all({category: "Food"})
  end
end
